name: Unit tests (JVM)

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - verdd
      - 'cit/**'
      - 'ci/**'
  pull_request:
    types:
      - ready_for_review
jobs:
  build:
    runs-on: "ve"
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests in the key projects
        run: sbt -v test "tpcbench-run / test" "tracing / test"
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
